package orderbuilder

import (
	"fmt"
	"strings"

	"github.com/major/schwab-agent/internal/models"
)

// ValidateOrderRequest validates a raw Schwab order request before preview or placement.
//
// Typed CLI builders validate their parameter structs before constructing JSON,
// but spec mode accepts arbitrary JSON from files, stdin, or inline flags. These
// checks catch the high-confidence shape errors locally so agents do not spend a
// Schwab API round trip discovering missing legs, quantities, symbols, or prices.
func ValidateOrderRequest(order *models.OrderRequest) error {
	return validateOrderRequest(order, "order")
}

// validateOrderRequest recursively validates a raw order and any child strategies.
func validateOrderRequest(order *models.OrderRequest, path string) error {
	if order == nil {
		return validationError(path+" spec is required", "Provide a JSON order object")
	}

	strategy := order.OrderStrategyType
	if strategy == "" {
		// Schwab examples often omit orderStrategyType for simple orders. Treat an
		// omitted strategy as SINGLE so spec mode stays compatible with minimal raw
		// API payloads while still validating the order's semantic shape.
		strategy = models.OrderStrategyTypeSingle
	}

	//nolint:exhaustive // Spec mode supports only executable strategies that schwab-agent can validate locally.
	switch strategy {
	case models.OrderStrategyTypeSingle:
		return validateSingleOrderRequest(order, path)
	case models.OrderStrategyTypeOCO:
		return validateOCOOrderRequest(order, path)
	case models.OrderStrategyTypeTrigger:
		return validateTriggerOrderRequest(order, path)
	default:
		return validationError(
			path+" has unsupported orderStrategyType "+string(strategy),
			"Use SINGLE, OCO, or TRIGGER for order specs generated by schwab-agent",
		)
	}
}

// validateSingleOrderRequest validates a simple order that can be sent directly to Schwab.
func validateSingleOrderRequest(order *models.OrderRequest, path string) error {
	if err := validateExecutableOrderRequest(order, path); err != nil {
		return err
	}

	if len(order.ChildOrderStrategies) > 0 {
		return validationError(
			path+" SINGLE order cannot contain childOrderStrategies",
			"Use orderStrategyType TRIGGER or OCO for child order strategies",
		)
	}

	return nil
}

// validateExecutableOrderRequest validates fields for an order node that actually submits legs.
func validateExecutableOrderRequest(order *models.OrderRequest, path string) error {
	if order.OrderType == "" {
		return validationError(
			path+" orderType is required",
			"Set orderType to MARKET, LIMIT, STOP, STOP_LIMIT, or another Schwab order type",
		)
	}

	if err := validateOrderRequestPricing(order, path); err != nil {
		return err
	}

	if len(order.OrderLegCollection) == 0 {
		return validationError(path+" requires at least one order leg", "Add orderLegCollection with one or more legs")
	}

	for index := range order.OrderLegCollection {
		if err := validateOrderRequestLeg(
			&order.OrderLegCollection[index],
			fmt.Sprintf("%s.orderLegCollection[%d]", path, index),
		); err != nil {
			return err
		}
	}

	return nil
}

// validateOCOOrderRequest validates one-cancels-other containers and their children.
func validateOCOOrderRequest(order *models.OrderRequest, path string) error {
	if len(order.ChildOrderStrategies) == 0 {
		return validationError(
			path+" OCO order requires childOrderStrategies",
			"Add child orders that Schwab should link together",
		)
	}

	if len(order.OrderLegCollection) > 0 {
		return validationError(
			path+" OCO parent must not contain direct order legs",
			"Move executable legs into childOrderStrategies",
		)
	}

	return validateChildOrderRequests(order, path)
}

// validateTriggerOrderRequest validates first-triggers-second and bracket-style specs.
func validateTriggerOrderRequest(order *models.OrderRequest, path string) error {
	if len(order.ChildOrderStrategies) == 0 {
		return validationError(
			path+" TRIGGER order requires childOrderStrategies",
			"Add child orders that Schwab should activate after the parent fills",
		)
	}

	// A TRIGGER node is not just a container: Schwab bracket and first-triggers-second
	// specs keep the executable parent order legs on the TRIGGER itself, then attach
	// exit/follow-up orders as children. Validate the parent like a SINGLE order but
	// deliberately allow its childOrderStrategies so build -> preview/place pipelines
	// remain compatible with raw specs generated by schwab-agent.
	if err := validateExecutableOrderRequest(order, path); err != nil {
		return err
	}

	return validateChildOrderRequests(order, path)
}

// validateChildOrderRequests recursively validates every child order strategy.
func validateChildOrderRequests(order *models.OrderRequest, path string) error {
	for index := range order.ChildOrderStrategies {
		childPath := fmt.Sprintf("%s.childOrderStrategies[%d]", path, index)
		if err := validateOrderRequest(&order.ChildOrderStrategies[index], childPath); err != nil {
			return err
		}
	}

	return nil
}

// validateOrderRequestPricing catches local price requirements for common order types.
func validateOrderRequestPricing(order *models.OrderRequest, path string) error {
	//nolint:exhaustive // Only order types requiring positive price fields are handled here.
	switch order.OrderType {
	case models.OrderTypeLimit, models.OrderTypeLimitOnClose, models.OrderTypeStopLimit,
		models.OrderTypeTrailingStopLimit, models.OrderTypeNetDebit, models.OrderTypeNetCredit:
		if order.Price == nil || *order.Price <= 0 {
			return validationError(
				path+" "+string(order.OrderType)+" order requires a positive price",
				"Set price to a value greater than zero",
			)
		}
	}

	//nolint:exhaustive // Only order types requiring stop fields are handled here.
	switch order.OrderType {
	case models.OrderTypeStop, models.OrderTypeStopLimit:
		if order.StopPrice == nil || *order.StopPrice <= 0 {
			return validationError(
				path+" "+string(order.OrderType)+" order requires a positive stopPrice",
				"Set stopPrice to a value greater than zero",
			)
		}
	case models.OrderTypeTrailingStop, models.OrderTypeTrailingStopLimit:
		if order.StopPriceOffset == nil || *order.StopPriceOffset <= 0 {
			return validationError(
				path+" "+string(order.OrderType)+" order requires a positive stopPriceOffset",
				"Set stopPriceOffset to a value greater than zero",
			)
		}
	}

	if err := validateOrderRequestPriceLinkPair(order, path); err != nil {
		return err
	}

	return nil
}

// validateOrderRequestPriceLinkPair checks pointer-based price-link fields from raw specs.
func validateOrderRequestPriceLinkPair(order *models.OrderRequest, path string) error {
	basisSet := order.PriceLinkBasis != nil && *order.PriceLinkBasis != ""
	typeSet := order.PriceLinkType != nil && *order.PriceLinkType != ""
	if basisSet != typeSet {
		return validationError(
			path+" priceLinkBasis and priceLinkType must be specified together",
			"Set both priceLinkBasis and priceLinkType, or omit both fields",
		)
	}

	return nil
}

// validateOrderRequestLeg validates fields common to equity, option, and spread legs.
func validateOrderRequestLeg(leg *models.OrderLegCollection, path string) error {
	if leg == nil {
		return validationError(path+" is required", "Provide an order leg object")
	}

	if leg.Instruction == "" {
		return validationError(
			path+" instruction is required",
			"Set instruction to BUY, SELL, BUY_TO_OPEN, SELL_TO_CLOSE, or another Schwab instruction",
		)
	}

	if leg.Quantity <= 0 {
		return validationError(path+" quantity must be greater than zero", "Set quantity to a positive value")
	}

	return validateOrderRequestInstrument(&leg.Instrument, path+".instrument")
}

// validateOrderRequestInstrument validates the required instrument fields for a leg.
func validateOrderRequestInstrument(instrument *models.OrderInstrument, path string) error {
	if instrument == nil {
		return validationError(path+" is required", "Provide an instrument object for the order leg")
	}

	if instrument.AssetType == "" {
		return validationError(
			path+" assetType is required",
			"Set assetType to EQUITY, OPTION, or another Schwab asset type",
		)
	}

	if strings.TrimSpace(instrument.Symbol) == "" {
		return validationError(path+" symbol is required", "Set symbol to the tradable equity or OCC option symbol")
	}

	if instrument.AssetType == models.AssetTypeOption && instrument.OptionStrikePrice != nil &&
		*instrument.OptionStrikePrice <= 0 {
		return validationError(
			path+" optionStrikePrice must be greater than zero",
			"Use a positive option strike price",
		)
	}

	return nil
}
