package commands

const (
	accountSourceExplicit = "explicit"
	accountSourceDefault  = "default"
	accountSourcePreview  = "preview"

	groupIDAccountMgmt = "account-mgmt"
	groupIDMarketData  = "market-data"
	groupIDTools       = "tools"
	groupIDTrading     = "trading"

	annotationSkipAuth  = "skipAuth"
	annotationValueTrue = "true"

	commandUseAuth       = "auth"
	commandUseCompletion = "completion"
	commandUseBuild      = "build"
	commandUseEnvVars    = "env-vars"
	commandUseEquity     = "equity"
	commandUseFish       = "fish"
	commandUseInstrument = "instrument"
	commandUseList       = "list"
	commandUseOption     = "option"
	commandUseOrder      = "order"
	commandUsePowerShell = "powershell"
	commandUsePlace      = "place"
	commandUsePreview    = "preview"
	commandUseQuote      = "quote"
	commandUseRoot       = "schwab-agent"
	commandUseSymbol     = "symbol"
	commandUseBash       = "bash"
	commandUseZsh        = "zsh"

	groupTitleTools = "Tool Commands"

	indicatorNameMACD = "macd"
	indicatorNameSMA  = "sma"

	verificationStatePartial = "partial"

	flagBuy   = "buy"
	flagCall  = "call"
	flagClose = "close"
	flagOpen  = "open"
	flagPut   = "put"
	flagSell  = "sell"

	orderTypeAliasLimitOnClose  = "LOC"
	orderTypeAliasMarketOnClose = "MOC"

	durationAliasFillOrKill        = "FOK"
	durationAliasGoodTillCancel    = "GTC"
	durationAliasImmediateOrCancel = "IOC"

	dashboardKeyATR14                   = "atr_14"
	dashboardKeyATRPercent              = "atr_percent"
	dashboardKeyAvgVolume20             = "avg_volume_20"
	dashboardKeyBBandsLower             = "bbands_lower"
	dashboardKeyBBandsMiddle            = "bbands_middle"
	dashboardKeyBBandsUpper             = "bbands_upper"
	dashboardKeyClose                   = "close"
	dashboardKeyDatetime                = "datetime"
	dashboardKeyDistanceFromSMA21Pct    = "distance_from_sma_21_percent"
	dashboardKeyDistanceFromSMA50Pct    = "distance_from_sma_50_percent"
	dashboardKeyDistanceFromSMA200Pct   = "distance_from_sma_200_percent"
	dashboardKeyDistanceFromRange20Pct  = "distance_from_range_20_high_percent"
	dashboardKeyDistanceFromRange252Pct = "distance_from_range_252_high_percent"
	dashboardKeyMACD                    = "macd"
	dashboardKeyMACDHistogram           = "macd_histogram"
	dashboardKeyMACDSignal              = "macd_signal"
	dashboardKeyRange20High             = "range_20_high"
	dashboardKeyRange20Low              = "range_20_low"
	dashboardKeyRange252High            = "range_252_high"
	dashboardKeyRange252Low             = "range_252_low"
	dashboardKeyRelativeVolume          = "relative_volume"
	dashboardKeyRSI14                   = "rsi_14"
	dashboardKeySMA21                   = "sma_21"
	dashboardKeySMA50                   = "sma_50"
	dashboardKeySMA200                  = "sma_200"
	dashboardKeyVolume                  = "volume"
)
